jobs:
  build:
    working_directory: ~/angular-ci
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: angular-ci-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  test:
    working_directory: ~/angular-ci
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run: mkdir ~/junit
      - run:
          command: xvfb-run -a npm run test-headless
          name: ng headless tests
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always  
      - run:
          command: xvfb-run -a npm run e2e
          name: ng e2e tests
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build