version: 2
jobs:
  build:
    working_directory: ~/angular-ci
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: angular-ci-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  test:
    working_directory: ~/angular-ci
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-ci-{{ .Branch }}-{{ checksum "package.json" }}
      - run: xvfb-run -a npm run test-headless
      - run: xvfb-run -a npm run e2e
 workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
          requires:
            - build
